#ATTEMPT AT LINUX

GREEN=\033[38;5;046m
YELLOW =\033[38;5;220m
END=\033[0m
NEWSECTION = "$(GREEN)--------------------------------------------------$(END)"

NAME = FdF
LIBFT = ./libft/libft.a
CC = gcc
FLAGS = -Wall -Wextra -Werror
INCLUDES = -I$(LIBFT_HEADERS) -I$(MINILIBX_HEADERS)

#libft
LIBFT_DIRECTORY = ./libft/
LIBFT = $(LIBFT_DIRECTORY)libft.a
LIBFT_HEADERS = $(LIBFT_DIRECTORY)

HEADER = ./

#for linux -> sudo apt-get update && sudo apt-get install xorg libxext-dev zlib1g-dev libbsd-dev
MINILIBX_DIRECTORY			:= ./minilibx-linux/
MINILIBX			:= ${MINILIBX_DIRECTORY}libmlx.a

LIBRARIES			:= -L${LIBFT_DIRECTORY} -L${MINILIBX_DIRECTORY} -lft -lmlx -lXext -lX11 -lm
INCLUDES			:= -I./ -I${LIBFT_DIRECTORY} -I${MINILIBX_DIRECTORY}
#make sure you change include in .h

#for mac
#MINILIBX = $(MINILIBX_DIRECTORY)libmlx.a
#MINILIBX_DIRECTORY = ./minilibx/
#MINILIBX_HEADERS = $(MINILIBX_DIRECTORY)
#LIBRARIES = -lmlx -lm -lft -L$(LIBFT_DIRECTORY) -L$(MINILIBX_DIRECTORY) -framework OpenGL -framework AppKit

srcs =	main.c\
		get_from_file.c\
		utils.c\
		draw.c\
		fdf.c\
		calc_project.c\

SRCS = $(addprefix ./SRCS/, $(srcs))
OBJS = $(SRCS:c=o)

gnl_srcs =	get_next_line.c\
			get_next_line_utils.c\

GNL_SRCS = $(addprefix ./get_next_line/, $(gnl_srcs))
GNL_OBJS = $(GNL_SRCS:c=o)

.PHONY: all clean fclean re

all: $(NAME)

$(NAME): $(MINILIBX) $(LIBFT) $(GNL_OBJS) $(OBJS)
	@echo "$(YELLOW)Compiling FdF program...$(END)"
	@$(CC) $(CFLAGS) $(LIBRARIES) $(OBJS) $(GNL_OBJS) -o $(NAME) $(LIBRARIES) $(INCLUDES)
	@echo "$(GREEN)FdF program compiled!$(END)"
	@echo $(NEWSECTION)

$(LIBFT):
	@echo "$(YELLOW)Building libft library...$(END)"
	$(MAKE) -C ./libft
	@echo "$(GREEN)libft library built successfully!$(END)"
	@echo $(NEWSECTION)

$(MINILIBX):
	@echo "$(NAME): $(GREEN)Creating $(MINILIBX)...$(END)"
	@$(MAKE) -C $(MINILIBX_DIRECTORY)

clean:
	@echo "$(YELLOW)Removing object files...$(END)"
	@rm -rf ./SRCS/*.o
	@rm -rf ./get_next_line/*.o
	@$(MAKE) clean -C ./libft
	@$(MAKE) clean -C $(MINILIBX_DIRECTORY)
	@echo "$(GREEN)Object files deleted!$(END)"
	@echo $(NEWSECTION)

fclean: clean
	@echo "$(YELLOW)Removing object files and program...$(END)"
	$(MAKE) fclean -C ./libft
	@rm -rf libmlx.dylib
	@rm -rf $(NAME)
	@echo "$(GREEN)fclean completed!$(END)"
	@echo $(NEWSECTION)
	
re: fclean all
